fullnameOverride: "shra"
executor:
  image:
    registry: "registry.crowdstrike.com"
    repository: "falcon-selfhostedregistryassessment/release/falcon-registryassessmentexecutor"
    tag: "0.11.0"

  dbStorage:
    storageClass: "standard"

  assessmentStorage:
    type: "local"

jobController:
  image:
    registry: "registry.crowdstrike.com"
    repository: "falcon-selfhostedregistryassessment/release/falcon-jobcontroller"
    tag: "0.19.0"

  dbStorage:
    storageClass: "standard"

crowdstrikeConfig:
  clientID: "abcdefABCDEF0123456789abcdefABCD"
  clientSecret: "abcdefABCDEF0123456789abcdefABCDEF012345"

registryConfigs:
  - type: dockerhub
    credentials:
      username: "userName"
      password: "password"
    port: "443"
    host: "https://registry-1.docker.io"
    cronSchedule: "* * * * *"
