{{- if not .Values.falcon.existingSecret -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "falcon-integration-gateway.fullname" . }}-creds
  labels:
     {{- include "falcon-integration-gateway.labels" . | nindent 4 }}
data:
  FALCON_CLIENT_ID: {{ .Values.falcon.client_id | b64enc }}
  FALCON_CLIENT_SECRET: {{ .Values.falcon.client_secret | b64enc }}
  FALCON_CLOUD_REGION: {{ .Values.falcon.cloud_region | b64enc }}
{{- if .Values.push.azure_log_analytics.enabled }}
  WORKSPACE_ID: {{ .Values.push.azure_log_analytics.workspace_id | b64enc }}
  PRIMARY_KEY: {{ .Values.push.azure_log_analytics.primary_key | b64enc }}
{{- end }}
{{- if .Values.push.chronicle.enabled }}
  CUSTOMER_ID: {{ .Values.push.chronicle.customer_id | b64enc }}
{{- end }}
{{- if .Values.push.cloudtrail_lake.enabled }}
  CLOUDTRAIL_LAKE_CHANNEL_ARN: {{ .Values.push.cloudtrail_lake.channel_arn | b64enc }}
{{- end }}
{{- if .Values.push.vmware_workspace_one.enabled }}
  WORKSPACEONE_TOKEN: {{ .Values.push.vmware_workspace_one.token | b64enc }}
{{- end }}
{{- end }}
