{{- if .Values.container.enabled }}
{{- if .Values.container.image.pullSecrets.enable }}
{{- $imagePullSecretName := (include "falcon-sensor.imagePullSecretName" .) }}
{{- if not ($imagePullSecretName) }}
{{- $registryConfigJson := (include "falcon-sensor.registryConfigJson" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $imagePullSecretName | default (printf "%s-pull-secret" (include "falcon-sensor.fullname" .)) }}
  namespace: {{ include "falcon-sensor.namespace" . }}
data:
  .dockerconfigjson: {{ $registryConfigJson }}
type: kubernetes.io/dockerconfigjson
{{- if or .Values.container.image.pullSecrets.namespaces .Values.container.image.pullSecrets.allNamespaces }}
{{- $name := ( $imagePullSecretName | default (printf "%s-pull-secret" (include "falcon-sensor.fullname" .))) }}
{{- $myns := split "," .Values.container.image.pullSecrets.namespaces | default "" -}}
{{- if .Values.container.image.pullSecrets.allNamespaces }}
{{- $myns = list -}}
{{- range $index, $ns := (lookup "v1" "Namespace" "" "").items -}}
  {{ $myns = append $myns $ns.metadata.name }}
{{- end }}
{{- end }}
{{- range $value := $myns }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ $value }}
data:
  .dockerconfigjson: {{ $registryConfigJson }}
type: kubernetes.io/dockerconfigjson
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
