{{- if and .Values.falconSecrets.enabled (not .Values.falconSecrets.existingSecretName) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "falcon-sensor.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "falcon-sensor.labels" . | nindent 4 }}
data:
  FALCONCTL_OPT_CID: {{ .Values.falcon.cid | b64enc | quote }}
  {{- if .Values.falcon.provisioning_token }}
  FALCONCTL_OPT_PROVISIONING_TOKEN: {{ .Values.falcon.provisioning_token | b64enc | quote }}
  {{- end }}
{{- end }}