{{- if and .Values.node.enabled .Values.node.hooks.postDelete.enabled }}
{{- if (include "registryConfigJson" .) }}
{{- $registryConfigJson := (include "registryConfigJson" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "falcon-sensor.fullname" . }}-pull-secret-cleanup
  namespace: {{ .Release.Namespace }}
  {{- if not .Values.node.cleanupOnly }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded
  {{- end }}
data:
  .dockerconfigjson: {{ $registryConfigJson }}
type: kubernetes.io/dockerconfigjson
{{- end }}
{{- end }}
