{{- if and .Values.node.enabled .Values.node.hooks.postDelete.enabled }}
{{- if .Values.node.image.registryConfigJSON }}
{{- $registry := .Values.node.image.registryConfigJSON }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "falcon-sensor.fullname" . }}-pull-secret-cleanup
  namespace: {{ include "falcon-sensor.namespace" . }}
  {{- if not .Values.node.cleanupOnly }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded
  {{- end }}
data:
  .dockerconfigjson: {{ $registry }}
type: kubernetes.io/dockerconfigjson
{{- end }}
{{- end }}
