{{- if and .Values.node.enabled .Values.node.hooks.postDelete.enabled }}
{{- if .Values.node.image.registryConfigJSON }}
{{- $registry := .Values.node.image.registryConfigJSON }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "falcon-sensor.fullname" . }}-pull-secret-cleanup
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-delete
data:
  .dockerconfigjson: {{ $registry }}
type: kubernetes.io/dockerconfigjson
{{- end }}
{{- end }}
