{{- if .Values.falcon.cid }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "falcon-sensor.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ include "falcon-sensor.name" . }}"
    app.kubernetes.io/name: {{ include "falcon-sensor.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: "container_sensor"
    crowdstrike.com/provider: crowdstrike
    helm.sh/chart: {{ include "falcon-sensor.chart" . }}
stringData:
  FALCONCTL_OPT_CID: {{ .Values.falcon.cid }}
{{- end }}
