{{- if and .Values.node.enabled .Values.node.hooks.postDelete.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}-node-cleanup
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: "kernel_sensor"
    helm.sh/chart: {{ include "falcon-sensor.chart" . }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "0"
{{- end }}
