apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "falcon-image-analyzer.fullname" . }}
  labels:
  {{- include "falcon-image-analyzer.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - secrets
    - services
    - namespaces
    - nodes
    verbs:
    - get
    - watch
    - list
