{{ if or (.Values.crowdstrikeConfig.dockerAPIToken) (.Values.image.registryConfigJSON) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "falcon-image-analyzer.fullname" . }}-pull-secret
  namespace: {{ include "falcon-image-analyzer.namespace" . }}
  labels:
  {{- include "falcon-image-analyzer.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
{{- if .Values.crowdstrikeConfig.dockerAPIToken }}
  .dockerconfigjson: {{ template "falcon-image-analyzer.imagePullSecret" . }}
{{- end }}
{{- if .Values.image.registryConfigJSON }}
  .dockerconfigjson: {{ .Values.image.registryConfigJSON }}
{{- end }}
{{- end }}
