{{- if .Values.pss.manageNamespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "falcon-image-analyzer.fullname" . }}-ns-labeler
  namespace: {{ include "falcon-image-analyzer.namespace" . }}
  labels:
    {{- include "falcon-image-analyzer.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "falcon-image-analyzer.fullname" . }}-ns-labeler
  labels:
    {{- include "falcon-image-analyzer.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "falcon-image-analyzer.fullname" . }}-ns-labeler
  labels:
    {{- include "falcon-image-analyzer.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
subjects:
  - kind: ServiceAccount
    name: {{ include "falcon-image-analyzer.fullname" . }}-ns-labeler
    namespace: {{ include "falcon-image-analyzer.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "falcon-image-analyzer.fullname" . }}-ns-labeler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "falcon-image-analyzer.fullname" . }}-ns-labeler
  namespace: {{ include "falcon-image-analyzer.namespace" . }}
  labels:
    {{- include "falcon-image-analyzer.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: {{ include "falcon-image-analyzer.fullname" . }}-ns-labeler
      restartPolicy: OnFailure
      containers:
        - name: kubectl
          image: docker.io/bitnami/kubectl
          command:
            - kubectl
            - label
            - namespace
            - {{ include "falcon-image-analyzer.namespace" . }}
            - "pod-security.kubernetes.io/enforce=privileged"
            - "pod-security.kubernetes.io/warn=privileged"
            - "pod-security.kubernetes.io/audit=privileged"
            - "--overwrite"
{{- end }}
