{{- $shouldCreateCid := include "falcon-image-analyzer.falconCid" . | trim -}}
{{- $shouldCreateClientCreds := include "falcon-image-analyzer.shouldCreateClientCredsInSecret" . | trim | eq "true" -}}
{{- if or $shouldCreateCid $shouldCreateClientCreds -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "falcon-image-analyzer.fullname" . }}
  namespace: {{ include "falcon-image-analyzer.namespace" . }}
  labels:
  {{- include "falcon-image-analyzer.labels" . | nindent 4 }}
data:
  {{- if $shouldCreateClientCreds }}
  AGENT_CLIENT_ID: {{ .Values.crowdstrikeConfig.clientID | b64enc | quote }}
  AGENT_CLIENT_SECRET: {{ .Values.crowdstrikeConfig.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if $shouldCreateCid }}
  AGENT_CID: {{ (include "falcon-image-analyzer.falconCid" .) | b64enc | quote }}
  {{- end }}
{{- end }}
