{{ if .Values.crowdstrikeConfig.dockerAPIToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cs-k8s-protection-agent.fullname" . }}-regsecret
  labels:
  {{- include "cs-k8s-protection-agent.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
  {{- end}}