{{- if (not .Values.crowdstrikeConfig.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cs-k8s-protection-agent.fullname" . }}
  labels:
  {{- include "cs-k8s-protection-agent.labels" . | nindent 4 }}
data:
  AGENT_CLIENT_ID: {{ required "A valid crowdstrike client ID is required" .Values.crowdstrikeConfig.clientID | b64enc | quote }}
  AGENT_CLIENT_SECRET: {{ required "A valid crowdstrike client secret is required" .Values.crowdstrikeConfig.clientSecret | b64enc | quote }}
{{- end }}