apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ra-self-hosted-executor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "ra-self-hosted.labels-executor" . | nindent 4 }}
