{{ if .Values.executor.image.registryConfigJSON }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ra-self-hosted-executor.pullsecret-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "ra-self-hosted.labels-executor" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
{{- if .Values.executor.image.registryConfigJSON }}
  .dockerconfigjson: {{ .Values.executor.image.registryConfigJSON }}
{{- end }}
{{- end }}
