apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ra-self-hosted-executor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "ra-self-hosted.labels-executor" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ra-self-hosted-executor.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ra-self-hosted-executor.fullname" . }}
