apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ra-self-hosted-executor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "ra-self-hosted.labels-executor" . | nindent 4 }}
rules:
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - get
    - watch
    - list
