{{- if and (eq (.Values.executor.storageEngine | default .Values.storageEngine) "postgres") (not .Values.postgresql.enabled) (not .Values.externalPostgresql.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ra-self-hosted-executor.fullname" . }}-external-postgres
  labels:
    {{- include "ra-self-hosted.labels-executor" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.externalPostgresql.password | quote }}
{{- end }}
