{{ if .Values.jobController.image.registryConfigJSON }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ra-self-hosted-job-controller.pullsecret-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "ra-self-hosted-job-controller.labels" . | nindent 8 }}
type: kubernetes.io/dockerconfigjson
data:
{{- if .Values.jobController.image.registryConfigJSON }}
  .dockerconfigjson: {{ .Values.jobController.image.registryConfigJSON }}
{{- end }}
{{- end }}
